apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "quote-app.redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.ports.redis }}
      targetPort: {{ .Values.redis.ports.redis }}
